US05 - Dodanie graczy
lukasz-stasiak/WheelOfFortune pull request #5
Opened 2022-03-10 20:25 UTC by lukasz-stasiak

Poproszę o sprawdzenie :) Coś mi się wydaję, że try, catch będzie do zmiany. 
Dzieki

2022-03-11 22:00 UTC, clockworkjava requested changes
Koniecznie nazwy zmiennych i metod na angielskie zmien. Drugi komentarz to raczej sugestia, poza nazwami dobrze jest.

2022-03-11 22:00 UTC, clockworkjava commented on src/main/java/pl/javagame/App.java
> +        ArrayList<Player> listaGraczy = new ArrayList<>();
Nazwy zmiennych, metod koniecznie po angielsku

2022-03-11 22:00 UTC, clockworkjava commented on src/main/java/pl/javagame/App.java
> +        Scanner scanner = new Scanner(System.in);
Zamiast tworzyc nowy scanner tutaj mozna przekazac Scanner jako parametr metody i przeslac ten stworzony w main

2022-03-12 08:54 UTC, clockworkjava commented on src/main/java/pl/javagame/App.java
> +        //Scanner scanner = new Scanner(System.in);
Nie ma sensu zakomentowywać kodu jak masz gita, jeśli będziesz chciał wrócić to zawsze można z historii gita wyciągnąć.

2022-03-12 08:55 UTC, clockworkjava commented on src/main/java/pl/javagame/App.java
> +        int noOfPlayers = scanner.nextInt();
i z doświadczenia - lepiej nie robić skrótowych nazw tylko pelne pisać- numberOfPlayers

2022-03-12 08:55 UTC, clockworkjava approved these changes
Dwie drobne uwagi na przyszłość, można mergować.

2022-03-12 09:03 UTC, lukasz-stasiak commented
Dzięki!

2022-03-12 09:03 UTC, merged