US08 Losowanie unikalnych haseł, HashMap?
lukasz-stasiak/WheelOfFortune pull request #8
Opened 2022-04-09 08:59 UTC by lukasz-stasiak

Mogę prosić o review? :)

2022-04-09 15:37 UTC, clockworkjava requested changes
Komentarze w kodzie

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        passwords.put("Cwiczenie czyni mistrza", true);
Czemu to akurat `true` ?

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        String Password = null;
z małej litery `Password`

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        String getKey;
zmienne nazywamy od rzeczowników,  getKey i getValue to raczej dla metod nazwy. Może po prostu `currentKey` i `currentValue`?

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        Integer max = passwords.keySet().toArray().length;// result=6
zamiast `max` to może lepiej `numberOfPasswords`, ten `max` mówi tak zupełnie nic ;)

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        Object randomPassword = passwords.keySet().toArray()[new Random().nextInt(max)];
Czemu `Object`? Powinien być typ `String`

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +
Dodatkowo ten `passwords.keySet().toArray()` trzymałbym w osobnej zmiennej lokalnej, bo jeszcze niżej jest wołany. Będzie wygodniej

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +    public Object checkigRandomPassword(Object randomPassword2) {
Nie używaj `Object`, zawsze konkretne typy. W tym wypadku `String`

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        Object randomPassword = passwords.keySet().toArray()[new Random().nextInt(max)];
Dodatkowo max może być 6, natomiast inteksuje się tablica od zera i [6] rzuci `OutOfBoundsException`
Powinno być `max-1`

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        for (Map.Entry<String, Boolean> map : passwords.entrySet()) {
Szczerze mówiąc nie rozumiem zasady działania tego fora.
Wyżej wylosowałeś hasło. 
Teraz trzebaby sprawdzić czy  passwords.get(randomPassword)==true, jeśli tak to je zwracamy, jeśli nie to losujemy kolejne.
Generalnie tak bym to widział
```
public String getRandomPassword() {
List<String> passwordsAsArray = passwords.keySet().toArray();

while(areThereUnusedPasswords()) {
String randomPassword  = passwordsAsArray[new Random().nextInt(max-1)];
if(passwords.get(randomPassword)) {
   password = randomPassword;
   passwords.set(randomPassword ,true)
   return password;
}
}
throw new IllegalStateException("No unused passwrods left");
}
private boolean areThereUnuseadPasswords() {
  for (Map.Entry<String, Boolean> entry : passwords.entrySet()) {
             if(entry.getValue()) return true;
  }
  return false;
}

2022-04-09 15:37 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +        for (Map.Entry<String, Boolean> map : passwords.entrySet()) {
Ta metoda jest gdzieś używana generalnie?

2022-06-09 22:21 UTC, clockworkjava commented on src/main/java/pl/javagame/PasswordManager.java
> +    // private ArrayList<String> copyPasswords = new ArrayList<>();
Jak kod niepotrzebny to wywalaj, nie ma sensu trzymac zakomentowanego, w razie czego jest w kontroli wersji poprzednia wersja i zawsze mozna wrócic

2022-06-09 22:22 UTC, clockworkjava approved these changes

2022-06-14 06:46 UTC, lukasz-stasiak commented
dzieki :)

2022-06-14 06:46 UTC, merged